---
abstract: 'Locate original perl script'
author:
  - 'Humberto Massa <massa@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: scriptname
requires:
  Carp: 0
  Cwd: 0
  Exporter: 0
  File::Basename: 0
  perl: 5.000
  strict: 0
  warnings: 0
version: 0.94
